
mysql:
  database: moonmoonbird
  user: root
  password: PengKim@123
  host: 192.168.0.108
  port: 3306

mongodb:
  host: localhost
  port: 27017
  database: moonmoonbird
  max_pool_size: 20

host: 127.0.0.1
port: 8080